version: "3.9"

services:
  attack_env:
    container_name: attack_env
    build:
      context: "./"
      dockerfile: "./dockerfile"
      args:
        USERNAME: ${USERNAME:-user}
        USERPASS: ${USERPASS:-1234}
        ROOTPASS: ${ROOTPASS:-1234}
        PACKAGES: ${PACKAGES:-}
        LINK_CHROME: ${LINK_CHROME:-}
        LINK_VSCODE: ${LINK_VSCODE:-}
        LINK_BURP: ${LINK_BURP:-}
        LINK_JAVA: ${LINK_JAVA:-}
        SEC_LIST: ${SEC_LIST:-}
        GIT_EMAIL: ${GIT_EMAIL:-}
        GIT_NAME: ${GIT_NAME:-}
    environment:
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
      - LC_ALL=en_US.UTF-8
      - DISPLAY=${DISPLAY}
      - TERM=xterm
    cap_add:
      - NET_ADMIN     # for wireshark
      - NET_RAW       #
    security_opt:
      - seccomp:unconfined #for chrome
    network_mode: "host"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix # for gui
      - user_home:/home/${USERNAME:-user}

volumes:
  user_home:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './Shared/home/'
